global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend service (FastAPI)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    # Add service label for better organization
    metric_relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '.*'
        replacement: 'backend'

  # Frontend service (Flask)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    # Add service label for better organization
    metric_relabel_configs:
      - source_labels: [__address__]
        target_label: service
        regex: '.*'
        replacement: 'frontend'

  # Node exporter (if you want system metrics)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker metrics (if you want container metrics)
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker:9323']
